name: Windows Perl tests

on:
  workflow_dispatch:
  push:
    tags:
    - "wintest-*"

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Perl...
        shell: powershell
        run: |
          choco install strawberryperl imagemagick -y
          echo 'C:\Strawberry\perl\bin' >> $env:GITHUB_PATH
          echo 'C:\Strawberry\c\bin' >> $env:GITHUB_PATH

      - name: Get dependencies...
        run: |
          cpanm -n -q Test2::V1 Capture::Tiny

      - name: Test...
        run: prove -lv t

      - name: Build Windows executable...
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force dist

          # prep the packed EXE version of the app with perl one-line hackeries
          perl -ne 'BEGIN { open STDOUT, q[>], q[dist/xmrf.pod] or die $! } $p ||= /^__END__$/; print if $p && !/^__END__$/' bin/xmrf
          perl -i -pe 's/#\*EXE POD\*#/my\$pod=PAR::read_file(q[xmrf.pod]);open(my\$pfh,q[<],\\\$pod) or die \$!;/' lib/xmrf/app.pm
          perl -i -pe 's/-input => \$0/-input => \$pfh/' lib/xmrf/app.pm
          perl -i -pe 's/use strict;/use strict;use PAR;/' lib/xmrf/app.pm

          # build an icon
          magick .github/public/xmrf.svg `
            -background none `
            -define icon:auto-resize=256,128,96,64,48,32,24,16 `
            dist/xmrf.ico

          # build exe
          pp -I lib `
            -a 'dist/xmrf.pod;xmrf.pod' `
            --icon dist/xmrf.ico `
            -o dist/xmrf.exe bin/xmrf

          Get-Item .\dist\xmrf.exe | Format-List Name, Length, FullName
          Get-Command .\dist\xmrf.exe

      - name: Smoke test...
        shell: powershell
        run: |
          $smoke = Join-Path $env:RUNNER_TEMP 'xmrf-smoke'
          New-Item -ItemType Directory -Force $smoke | Out-Null
          Copy-Item .\dist\xmrf.exe $smoke

          Set-Location $smoke

          .\xmrf.exe "(.*)" "%s"

          if ($LASTEXITCODE -ne 0) {
            throw "xmrf smoke test failed with exit code $rc"
          }

          .\xmrf.exe --help

      - name: Upload Windows executable...
        uses: actions/upload-artifact@v4
        with:
          name: xmrf-windows
          path: dist/xmrf.exe
